const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const catalog=JSON.parse(fs.readFileSync(__dirname+'/assets/catalog.json','utf8'));
const evening=catalog.events.filter(e=>e.unit==='450047+450119'&&e.date==='2026-08-20'&&e.time==='19:48');
assert.deepEqual(evening.map(e=>e.side).sort(),['A','B']);
// Fix the assessment fixture: the user's live annotations continue evolving.
evening.forEach(e=>e.carriages.forEach(c=>{c.assessed=false;c.defects=[];}));
assert(evening.every(e=>e.washed&&e.mode==='panorama'&&e.carriages.length===8&&e.carriages.every(c=>!c.assessed)));
assert(evening.every(e=>e.id.endsWith('-1948')));
assert.equal(new Set(catalog.events.map(e=>e.id)).size,catalog.events.length);
const nodes=new Map();const node=s=>{if(!nodes.has(s))nodes.set(s,{value:s==='[data-period-mode]'?'calendar':'',innerHTML:'',append(){},addEventListener(){},classList:{toggle(){}},setAttribute(){}});return nodes.get(s);};
const ctx=vm.createContext({URL,URLSearchParams,Intl,Date,console,location:'http://localhost/index.html',history:{pushState(){}},window:{EYYA_CATALOG:catalog,addEventListener(){},scrollTo(){}},document:{querySelector:node,addEventListener(){}}});
vm.runInContext(fs.readFileSync(__dirname+'/assets/fleet.js','utf8'),ctx);
assert.equal(new Set(catalog.events.map(e=>e.id)).size,catalog.events.length);
assert.equal(catalog.events.filter(e=>e.sourceFolder.endsWith('0904')).length,6);
assert.equal(catalog.events.filter(e=>e.sourceFolder.endsWith('0907')&&e.carriages.length===10).length,2);
assert.equal(catalog.events.filter(e=>/(0919|0920)$/.test(e.sourceFolder)).length,21);
for(const unit of ['450015+450057','450047+450119']){
  const sides=catalog.events.filter(e=>e.unit===unit&&e.date==='2026-08-19'&&e.mode==='panorama');
  assert.deepEqual(sides.map(e=>e.side).sort(),['A','B']);
  assert(sides.every(e=>e.carriages.length===8&&e.cover&&e.video));
}
vm.runInContext("activeDate='2026-08-19'; $('[data-period-mode]').value='overnight'; render();",ctx);
const stats=vm.runInContext("({captures:sessions(filtered()).length,units:new Set(filtered().map(e=>e.unit)).size,carriages:[...new Set(filtered().map(e=>e.unit))].reduce((n,u)=>n+carriageCount(u),0),wash:sessions(filtered()).filter(s=>s.items.some(e=>e.washed)).length})",ctx);
assert.equal(stats.captures,24);assert.equal(stats.units,10);assert.equal(stats.carriages,90);assert.equal(stats.wash,11);
// Explicit boundaries: evening included, early morning excluded at 07:00.
vm.runInContext(`catalog.events.push(...['18:59','19:00'].map(time=>({unit:'999999',date:'2026-08-19',time})),...['06:59','07:00'].map(time=>({unit:'999999',date:'2026-08-20',time})));`,ctx);
assert.equal(vm.runInContext("filtered().filter(e=>e.unit==='999999').map(e=>e.time).sort().join(',')",ctx),'06:59,19:00');
vm.runInContext("catalog.events=catalog.events.filter(e=>e.unit!=='999999')",ctx);
vm.runInContext("route('701042')",ctx);
const html=node('[data-dashboard]').innerHTML;
assert.equal((html.match(/class="carriage-chart"/g)||[]).length,10);
assert(html.includes('&amp;carriage=480042'));assert(html.includes('Not assessed'));
assert(!html.includes('Not recorded'));assert(!html.includes('◆ Washed'));
assert.equal((html.match(/class="chart-wash /g)||[]).length,20);
assert(html.includes('data-video-event="701042-2026-08-10-A"'));
assert(html.includes('data-video-event="701042-2026-08-19-A"'));
assert(html.includes('issue-severe issue-metric'));
assert(html.includes('highlight=severe'));
assert(!html.includes('<aside'));
assert(html.includes('Non-compliant · Graffiti'));
const graffitiChart=vm.runInContext("chart('482042',catalog.events.filter(e=>e.unit==='701042'&&e.side==='A'&&e.mode==='panorama'))",ctx);
assert.equal((graffitiChart.match(/fill=\"#8054c9\"/g)||[]).length,3);
assert.equal((graffitiChart.match(/Graffiti present/g)||[]).length,3);
assert.equal(vm.runInContext("chartColour({assessed:true,cleanliness:'Non-Compliant',defects:[]})",ctx),'#e34e53');
assert.equal(vm.runInContext("chartColour({assessed:false,defects:[{type:'graffiti'}]})",ctx),'#fff');
vm.runInContext("route('701022')",ctx);
let sideHtml=node('[data-dashboard]').innerHTML;
assert(sideHtml.includes('history · Side A'));
assert(!sideHtml.includes('event=701022-2026-07-16-B'));
vm.runInContext("historySide='B';render()",ctx);
sideHtml=node('[data-dashboard]').innerHTML;
assert(sideHtml.includes('history · Side B'));
assert(!sideHtml.includes('event=701022-2026-08-01-A'));
vm.runInContext("route('701048')",ctx);
assert(!node('[data-dashboard]').innerHTML.includes('event=701048-2026-07-04-B'));
vm.runInContext("historySide='B';render()",ctx);
assert(!node('[data-dashboard]').innerHTML.includes('event=701048-2026-07-04-A'));
const markers=vm.runInContext("washMarkers([{e:{date:'2026-08-10',time:'19:21'}},{e:{date:'2026-08-14',time:'05:51'}},{e:{date:'2026-08-20',time:'05:39'}}],[{date:'2026-08-10',time:'19:21'},{date:'2026-08-19',time:'23:31'}],i=>35+i*90)",ctx);
const xs=[...markers.matchAll(/translate\(([\d.]+),8\)/g)].map(m=>Number(m[1]));
assert(xs[0]>35&&xs[0]<125);assert(xs[1]>125&&xs[1]<215);
console.log('Fleet checks passed:',stats);
const latest=vm.runInContext(`latestIssue([
{id:'old',mode:'panorama',date:'2026-08-01',time:'20:00',carriages:[{order:0,serial:'480042',defects:[{type:'graffiti'}]}]},
{id:'new',mode:'panorama',date:'2026-08-20',time:'05:00',carriages:[{order:0,serial:'481042',defects:[{type:'graffiti'}]}]},
{id:'new-clean',mode:'panorama',date:'2026-08-21',time:'05:00',carriages:[{order:0,serial:'482042',defects:[]}]}
], 'graffiti')`,ctx);
assert.equal(latest,'event.html?event=new&carriage=481042&highlight=graffiti');
assert.equal(vm.runInContext("latestIssue([], 'severe')",ctx),'');
vm.runInContext("route('');activeDate='*';render()",ctx);
const overview=node('[data-dashboard]').innerHTML;
assert(overview.includes('Potential water saving'));assert(!overview.includes('Train classes'));assert(!overview.includes('<h2>Train history'));
assert(overview.includes('highlight=graffiti'));assert(node('[data-history-select]').innerHTML.includes('701042'));
let onLoad, jumped;
vm.runInNewContext(fs.readFileSync(__dirname+'/assets/event.js','utf8').split('const capture =')[0],{window:{addEventListener:(name,fn)=>{onLoad=fn;}},URLSearchParams,location:{search:'?carriage=481042&highlight=graffiti'},jump:(...args)=>{jumped=args;}});
onLoad();assert.deepEqual(jumped,['481042','graffiti']);
console.log('Issue navigation passed: latest matching capture, empty results, flash on arrival');
vm.runInContext("route('701042')",ctx);
assert(!node('[data-dashboard]').innerHTML.includes('<h1>Fleet overview'));
assert(!node('[data-dashboard]').innerHTML.includes('Wash-entry records'));
assert(node('[data-dashboard]').innerHTML.includes('data-overview'));
assert.equal(node('.fleet-toolbar').hidden,true);
vm.runInContext("route('')",ctx);
assert(!node('[data-dashboard]').innerHTML.includes('Wash-entry records'));
assert(node('[data-dashboard]').innerHTML.includes('metric-icon'));
assert.equal(node('.fleet-toolbar').hidden,false);
const totalSavings=vm.runInContext('savings(catalog.events)',ctx);
assert.equal(totalSavings.count,5);assert.equal(totalSavings.water,9900);assert.equal(totalSavings.cost,910);
assert(overview.includes('225 L per carriage'));
assert(overview.includes('metric-open-cue'));
assert.equal(vm.runInContext("!!savingCase(catalog.events.find(e=>e.id==='450015+450057-2026-08-19-A'))",ctx),true);
assert.equal(vm.runInContext("!!savingCase(catalog.events.find(e=>e.id==='450047-2026-08-19-U'))",ctx),true);
for(const date of ['2026-08-04','2026-08-06'])assert.equal(vm.runInContext(`!!savingCase(catalog.events.find(e=>e.id==='701046-${date}-A'))`,ctx),false);
vm.runInContext("activeDate='*';featureFilters.wash=true;render()",ctx);
assert.equal(vm.runInContext('sessions(filtered()).every(s=>s.items.some(e=>e.washed))',ctx),true);
assert.equal(vm.runInContext('savings(filtered()).count',ctx),5);
vm.runInContext('featureFilters.avoidable=true',ctx);
assert.equal(vm.runInContext('sessions(filtered()).length',ctx),5);
assert.equal(vm.runInContext("filtered().some(e=>e.unit==='701046')",ctx),false);
vm.runInContext('featureFilters.avoidable=false',ctx);
const covers=vm.runInContext("sessions(filtered()).filter(s=>s.primary.unit==='701030'||(s.primary.unit==='701046'&&s.primary.date==='2026-08-06')).map(s=>s.cover)",ctx);
assert(covers.every(s=>s.endsWith('_B.jpg')));
vm.runInContext("route('701046');historySide='A';render()",ctx);
const history=node('[data-dashboard]').innerHTML;
assert.equal((history.match(/wash-opportunity-frame/g)||[]).length,0);
assert.equal((history.match(/data-video-event=\"701046-2026-08-06-A\"/g)||[]).length,10);
assert(!node('[data-capture-grid]').innerHTML.includes('avoidable-badge'));
vm.runInContext("route('450047+450119');historySide='A';render()",ctx);
const formationHtml=node('[data-dashboard]').innerHTML;
assert.equal((formationHtml.match(/class="formation-row"/g)||[]).length,2);
assert.deepEqual([...formationHtml.matchAll(/class="carriage-chart"><h3>(\d+)/g)].map(m=>m[1]),['63247','64247','68147','63647','63909','66929','66909','63929']);
assert(formationHtml.includes('20/8</tspan>')&&formationHtml.includes('5:30</tspan>')&&formationHtml.includes('19:48</tspan>'));
assert(!formationHtml.includes('rotate(-35)'));
assert(formationHtml.includes('event=450047%2B450119-2026-08-20-A-1948'));
assert(formationHtml.includes('Not assessed'));
const fourFifty=vm.runInContext("chart('63247',catalog.events.filter(e=>e.unit==='450047+450119'&&e.side==='A'&&e.mode==='panorama').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)),catalog.events.filter(e=>e.unit==='450047+450119'&&e.washed))",ctx);
const washXs=[...fourFifty.matchAll(/class="chart-wash [^"]*"[^>]*translate\(([\d.]+),8\)/g)].map(m=>Number(m[1]));
assert.equal(washXs.length,3);assert(washXs[1]-washXs[0]>=18);
assert.equal((fourFifty.match(/wash-opportunity-frame/g)||[]).length,2);
vm.runInContext("historySide='B';render()",ctx);
assert.deepEqual([...node('[data-dashboard]').innerHTML.matchAll(/class="carriage-chart"><h3>(\d+)/g)].map(m=>m[1]),['63247','64247','68147','63647','63909','66929','66909','63929']);
assert(fs.readFileSync(__dirname+'/assets/event.js','utf8').includes('item.time===capture.time'));
vm.runInContext("catalog.events.push({id:'458001-test-A',unit:'458001+458002',date:'2026-09-01',time:'19:00',side:'A',mode:'panorama',carriages:Array.from({length:8},(_,i)=>({serial:String(60001+i),order:i,assessed:false,defects:[]}))});route('458001+458002')",ctx);
assert.equal((node('[data-dashboard]').innerHTML.match(/class="formation-row"/g)||[]).length,2);
console.log('Side isolation, four-car formation order, spaced wash markers and 9900 L / £910 estimates passed');
